version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
     - ./volumes/mysql/:/var/lib/mysql
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
     - 3306:3306
    environment:
     MYSQL_ROOT_PASSWORD: changeit
     MYSQL_DATABASE: data-driven-test
     MYSQL_USER: data-driven-test
     MYSQL_PASSWORD: changeit
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8081:80
    volumes:
     - /sessions
  selenium-firefox:
      image: selenium/standalone-firefox-debug:3.14.0-beryllium
      container_name: ft-selenium-firefox-3-14
      ports:
       - 4444:4444
       - 5900:5900